apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  namespace: my-namespace
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d79e0933e102fde7


